package budjetoija.kayttoliittyma;

import budjetoija.logiikka.Tili;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JSpinner;

public class GUI extends javax.swing.JFrame implements Runnable{

    Tili tili;
    GregorianCalendar paivamaara;
    
    
    public GUI(Tili tili) {
        this.tili = tili;
        this.paivamaara = new GregorianCalendar();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        initComponents();
    }
    
    @Override
    public void run() {
        this.setVisible(true);
    }
                        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paaPaneeli = new javax.swing.JPanel();
        listausScrollPane = new javax.swing.JScrollPane();
        listausList = new javax.swing.JList();
        ylaPaneeli = new javax.swing.JPanel();
        lisaaTilitapahtumaButton = new javax.swing.JButton();
        poistaTilitapahtumaButton = new javax.swing.JButton();
        lataaTiliButton = new javax.swing.JButton();
        tallennaTiliButton = new javax.swing.JButton();
        hallitseTilitapahtumiaLabel = new javax.swing.JLabel();
        hallitseTiliaLabel = new javax.swing.JLabel();
        uusiTiliButton = new javax.swing.JButton();
        nakymaKuukausiLabel = new javax.swing.JLabel();
        nakymaVuosiLabel = new javax.swing.JLabel();
        nakymaLabel = new javax.swing.JLabel();
        nakymaMeneButton = new javax.swing.JToggleButton();
        nakymaKuukausiSpinner = new javax.swing.JSpinner();
        nakymaVuosiSpinner = new javax.swing.JSpinner();
        sivuPalkki = new javax.swing.JPanel();
        kuvausLabel = new javax.swing.JLabel();
        kuvausTextField = new javax.swing.JTextField();
        summaLabel = new javax.swing.JLabel();
        summaTextField = new javax.swing.JTextField();
        paivaLabel = new javax.swing.JLabel();
        paivaTextField = new javax.swing.JTextField();
        kuukausiLabel = new javax.swing.JLabel();
        kuukausiTextField = new javax.swing.JTextField();
        vuosiLabel = new javax.swing.JLabel();
        vuosiTextField = new javax.swing.JTextField();
        tallennaButton = new javax.swing.JButton();
        toistuvaAlkuPaivaLabel = new javax.swing.JLabel();
        toistuvaAlkuPaivaTextField = new javax.swing.JTextField();
        toistuvaAlkuKuukausiLabel = new javax.swing.JLabel();
        toistuvaAlkuKuukausiTextField = new javax.swing.JTextField();
        toistuvaAlkuVuosiTextField = new javax.swing.JTextField();
        toistuvaAlkuVuosiLabel = new javax.swing.JLabel();
        toistuvuusCheckBox = new javax.swing.JCheckBox();
        toistuvaLoppuKuukausiLabel = new javax.swing.JLabel();
        toistuvaLoppuKuukausiTextField = new javax.swing.JTextField();
        toistuvaLoppuPaivaLabel = new javax.swing.JLabel();
        toistuvaLoppuPaivaTextField = new javax.swing.JTextField();
        toistuvaLoppuVuosiTextField = new javax.swing.JTextField();
        toistuvaLoppuVuosiLabel = new javax.swing.JLabel();
        yhteenvetoPane = new javax.swing.JScrollPane();
        yhteenvetoTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buddy - pientalouden budjetoija");
        setPreferredSize(new java.awt.Dimension(800, 570));
        setResizable(false);

        listausList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listausScrollPane.setViewportView(listausList);

        lisaaTilitapahtumaButton.setText("Lisää");
        lisaaTilitapahtumaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaTilitapahtumaButtonActionPerformed(evt);
            }
        });

        poistaTilitapahtumaButton.setText("Poista");
        poistaTilitapahtumaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poistaTilitapahtumaButtonActionPerformed(evt);
            }
        });

        lataaTiliButton.setText("Lataa");
        lataaTiliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lataaTiliButtonActionPerformed(evt);
            }
        });

        tallennaTiliButton.setText("Tallenna");

        hallitseTilitapahtumiaLabel.setText("Hallitse tilitapahtumia");

        hallitseTiliaLabel.setText("Hallitse tiliä");

        uusiTiliButton.setText("Uusi");

        nakymaKuukausiLabel.setText("kk");

        nakymaVuosiLabel.setText("vuosi");

        nakymaLabel.setText("Näkymä");

        nakymaMeneButton.setText("Mene");
        nakymaMeneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nakymaMeneButtonActionPerformed(evt);
            }
        });

        nakymaKuukausiSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        nakymaVuosiSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(this.paivamaara.get(Calendar.YEAR)), Integer.valueOf(0), null, Integer.valueOf(1)));

        nakymaVuosiSpinner.setEditor(new JSpinner.NumberEditor(nakymaVuosiSpinner, "#"));

        javax.swing.GroupLayout ylaPaneeliLayout = new javax.swing.GroupLayout(ylaPaneeli);
        ylaPaneeli.setLayout(ylaPaneeliLayout);
        ylaPaneeliLayout.setHorizontalGroup(
            ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ylaPaneeliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ylaPaneeliLayout.createSequentialGroup()
                        .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nakymaKuukausiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nakymaKuukausiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nakymaVuosiSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(nakymaVuosiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nakymaMeneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nakymaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ylaPaneeliLayout.createSequentialGroup()
                        .addComponent(uusiTiliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tallennaTiliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lataaTiliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hallitseTiliaLabel))
                .addGap(59, 59, 59)
                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ylaPaneeliLayout.createSequentialGroup()
                        .addComponent(lisaaTilitapahtumaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poistaTilitapahtumaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hallitseTilitapahtumiaLabel))
                .addGap(23, 23, 23))
        );
        ylaPaneeliLayout.setVerticalGroup(
            ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ylaPaneeliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ylaPaneeliLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lataaTiliButton, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                    .addGroup(ylaPaneeliLayout.createSequentialGroup()
                        .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hallitseTilitapahtumiaLabel)
                            .addComponent(hallitseTiliaLabel)
                            .addComponent(nakymaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lisaaTilitapahtumaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uusiTiliButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tallennaTiliButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poistaTilitapahtumaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ylaPaneeliLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ylaPaneeliLayout.createSequentialGroup()
                                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nakymaKuukausiLabel)
                                    .addComponent(nakymaVuosiLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nakymaKuukausiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nakymaVuosiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nakymaMeneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        sivuPalkki.setMinimumSize(new java.awt.Dimension(200, 100));

        kuvausLabel.setText("Kuvaus");

        summaLabel.setText("Summa");

        paivaLabel.setText("pv");

        kuukausiLabel.setText("kk");

        vuosiLabel.setText("vuosi");

        tallennaButton.setText("Tallenna");
        tallennaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tallennaButtonActionPerformed(evt);
            }
        });

        toistuvaAlkuPaivaLabel.setText("pv");

        toistuvaAlkuPaivaTextField.setEnabled(false);

        toistuvaAlkuKuukausiLabel.setText("kk");

        toistuvaAlkuKuukausiTextField.setEnabled(false);

        toistuvaAlkuVuosiTextField.setEnabled(false);

        toistuvaAlkuVuosiLabel.setText("vuosi");

        toistuvuusCheckBox.setText("Toistuva tapahtuma");
        toistuvuusCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toistuvuusCheckBoxActionPerformed(evt);
            }
        });

        toistuvaLoppuKuukausiLabel.setText("kk");

        toistuvaLoppuKuukausiTextField.setEnabled(false);

        toistuvaLoppuPaivaLabel.setText("pv");

        toistuvaLoppuPaivaTextField.setEnabled(false);

        toistuvaLoppuVuosiTextField.setEnabled(false);

        toistuvaLoppuVuosiLabel.setText("vuosi");

        javax.swing.GroupLayout sivuPalkkiLayout = new javax.swing.GroupLayout(sivuPalkki);
        sivuPalkki.setLayout(sivuPalkkiLayout);
        sivuPalkkiLayout.setHorizontalGroup(
            sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sivuPalkkiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tallennaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kuvausTextField)
                    .addComponent(summaTextField)
                    .addComponent(kuvausLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(summaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sivuPalkkiLayout.createSequentialGroup()
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toistuvaAlkuPaivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toistuvaAlkuPaivaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toistuvaAlkuKuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toistuvaAlkuKuukausiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sivuPalkkiLayout.createSequentialGroup()
                                .addComponent(toistuvaAlkuVuosiLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(toistuvaAlkuVuosiTextField)))
                    .addGroup(sivuPalkkiLayout.createSequentialGroup()
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toistuvuusCheckBox)
                            .addGroup(sivuPalkkiLayout.createSequentialGroup()
                                .addComponent(paivaLabel)
                                .addGap(29, 29, 29)
                                .addComponent(kuukausiLabel)
                                .addGap(18, 18, 18)
                                .addComponent(vuosiLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sivuPalkkiLayout.createSequentialGroup()
                        .addComponent(paivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vuosiTextField))
                    .addGroup(sivuPalkkiLayout.createSequentialGroup()
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toistuvaLoppuPaivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toistuvaLoppuPaivaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toistuvaLoppuKuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toistuvaLoppuKuukausiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sivuPalkkiLayout.createSequentialGroup()
                                .addComponent(toistuvaLoppuVuosiLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(toistuvaLoppuVuosiTextField))))
                .addContainerGap())
        );
        sivuPalkkiLayout.setVerticalGroup(
            sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sivuPalkkiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kuvausLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kuvausTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(summaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(summaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paivaLabel)
                    .addComponent(kuukausiLabel)
                    .addComponent(vuosiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vuosiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(toistuvuusCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toistuvaAlkuPaivaLabel)
                    .addComponent(toistuvaAlkuKuukausiLabel)
                    .addComponent(toistuvaAlkuVuosiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toistuvaAlkuPaivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toistuvaAlkuKuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toistuvaAlkuVuosiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toistuvaLoppuPaivaLabel)
                    .addComponent(toistuvaLoppuKuukausiLabel)
                    .addComponent(toistuvaLoppuVuosiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toistuvaLoppuPaivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toistuvaLoppuKuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toistuvaLoppuVuosiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tallennaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kuvausTextField.getAccessibleContext().setAccessibleName("");

        yhteenvetoTextArea.setEditable(false);
        yhteenvetoTextArea.setColumns(20);
        yhteenvetoTextArea.setRows(5);
        yhteenvetoPane.setViewportView(yhteenvetoTextArea);

        javax.swing.GroupLayout paaPaneeliLayout = new javax.swing.GroupLayout(paaPaneeli);
        paaPaneeli.setLayout(paaPaneeliLayout);
        paaPaneeliLayout.setHorizontalGroup(
            paaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paaPaneeliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ylaPaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paaPaneeliLayout.createSequentialGroup()
                        .addGroup(paaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listausScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addComponent(yhteenvetoPane))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sivuPalkki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        paaPaneeliLayout.setVerticalGroup(
            paaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paaPaneeliLayout.createSequentialGroup()
                .addComponent(ylaPaneeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(paaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paaPaneeliLayout.createSequentialGroup()
                        .addComponent(listausScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yhteenvetoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sivuPalkki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(paaPaneeli, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lataaTiliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lataaTiliButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lataaTiliButtonActionPerformed

    private void poistaTilitapahtumaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poistaTilitapahtumaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poistaTilitapahtumaButtonActionPerformed

    private void lisaaTilitapahtumaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaTilitapahtumaButtonActionPerformed
        
    }//GEN-LAST:event_lisaaTilitapahtumaButtonActionPerformed

    private void toistuvuusCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toistuvuusCheckBoxActionPerformed
        paivaTextField.setEnabled(!paivaTextField.isEnabled());
        kuukausiTextField.setEnabled(!kuukausiTextField.isEnabled());
        vuosiTextField.setEnabled(!vuosiTextField.isEnabled());
        
        toistuvaAlkuPaivaTextField.setEnabled(!toistuvaAlkuPaivaTextField.isEnabled());
        toistuvaAlkuKuukausiTextField.setEnabled(!toistuvaAlkuKuukausiTextField.isEnabled());
        toistuvaAlkuVuosiTextField.setEnabled(!toistuvaAlkuVuosiTextField.isEnabled());
        toistuvaLoppuPaivaTextField.setEnabled(!toistuvaLoppuPaivaTextField.isEnabled());
        toistuvaLoppuKuukausiTextField.setEnabled(!toistuvaLoppuKuukausiTextField.isEnabled());
        toistuvaLoppuVuosiTextField.setEnabled(!toistuvaLoppuVuosiTextField.isEnabled());
    }//GEN-LAST:event_toistuvuusCheckBoxActionPerformed

    private void nakymaMeneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nakymaMeneButtonActionPerformed
        this.paivamaara.set(Calendar.YEAR, (Integer)nakymaVuosiSpinner.getValue());
        this.paivamaara.set(Calendar.MONTH, (Integer)nakymaKuukausiSpinner.getValue() - 1);
        this.setTitle("Buddy - pientalouden budjetoija - " + this.tili.getNimi() + " - "+ (this.paivamaara.get(Calendar.MONTH) + 1) +"/"+this.paivamaara.get(Calendar.YEAR));
    }//GEN-LAST:event_nakymaMeneButtonActionPerformed

    private void tallennaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tallennaButtonActionPerformed
        
    }//GEN-LAST:event_tallennaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hallitseTiliaLabel;
    private javax.swing.JLabel hallitseTilitapahtumiaLabel;
    private javax.swing.JLabel kuukausiLabel;
    private javax.swing.JTextField kuukausiTextField;
    private javax.swing.JLabel kuvausLabel;
    private javax.swing.JTextField kuvausTextField;
    private javax.swing.JButton lataaTiliButton;
    private javax.swing.JButton lisaaTilitapahtumaButton;
    private javax.swing.JList listausList;
    private javax.swing.JScrollPane listausScrollPane;
    private javax.swing.JLabel nakymaKuukausiLabel;
    private javax.swing.JSpinner nakymaKuukausiSpinner;
    private javax.swing.JLabel nakymaLabel;
    private javax.swing.JToggleButton nakymaMeneButton;
    private javax.swing.JLabel nakymaVuosiLabel;
    private javax.swing.JSpinner nakymaVuosiSpinner;
    private javax.swing.JPanel paaPaneeli;
    private javax.swing.JLabel paivaLabel;
    private javax.swing.JTextField paivaTextField;
    private javax.swing.JButton poistaTilitapahtumaButton;
    private javax.swing.JPanel sivuPalkki;
    private javax.swing.JLabel summaLabel;
    private javax.swing.JTextField summaTextField;
    private javax.swing.JButton tallennaButton;
    private javax.swing.JButton tallennaTiliButton;
    private javax.swing.JLabel toistuvaAlkuKuukausiLabel;
    private javax.swing.JTextField toistuvaAlkuKuukausiTextField;
    private javax.swing.JLabel toistuvaAlkuPaivaLabel;
    private javax.swing.JTextField toistuvaAlkuPaivaTextField;
    private javax.swing.JLabel toistuvaAlkuVuosiLabel;
    private javax.swing.JTextField toistuvaAlkuVuosiTextField;
    private javax.swing.JLabel toistuvaLoppuKuukausiLabel;
    private javax.swing.JTextField toistuvaLoppuKuukausiTextField;
    private javax.swing.JLabel toistuvaLoppuPaivaLabel;
    private javax.swing.JTextField toistuvaLoppuPaivaTextField;
    private javax.swing.JLabel toistuvaLoppuVuosiLabel;
    private javax.swing.JTextField toistuvaLoppuVuosiTextField;
    private javax.swing.JCheckBox toistuvuusCheckBox;
    private javax.swing.JButton uusiTiliButton;
    private javax.swing.JLabel vuosiLabel;
    private javax.swing.JTextField vuosiTextField;
    private javax.swing.JScrollPane yhteenvetoPane;
    private javax.swing.JTextArea yhteenvetoTextArea;
    private javax.swing.JPanel ylaPaneeli;
    // End of variables declaration//GEN-END:variables
}
