package budjetoija.kayttoliittyma;

import budjetoija.logiikka.Summa;
import budjetoija.logiikka.Tili;
import budjetoija.logiikka.Tilitapahtuma;
import budjetoija.logiikka.ToistuvaTilitapahtuma;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 * Budjetoijan käyttöliittymä.
 */

public class GUI extends javax.swing.JFrame implements Runnable{

    Tili tili;
    Calendar alkuPvm;
    Calendar loppuPvm;
    
    
    public GUI(Tili tili) {
        this.tili = tili;
        
        this.alkuPvm = new GregorianCalendar();
        this.alkuPvm.set(Calendar.DAY_OF_MONTH, 1);
        alkuPvm.clear(Calendar.HOUR);
        alkuPvm.clear(Calendar.MINUTE);
        alkuPvm.clear(Calendar.SECOND);
        alkuPvm.clear(Calendar.MILLISECOND);
        
        this.loppuPvm = new GregorianCalendar();
        this.loppuPvm.set(Calendar.DAY_OF_MONTH, this.loppuPvm.getActualMaximum(Calendar.DAY_OF_MONTH));
        loppuPvm.clear(Calendar.HOUR);
        loppuPvm.clear(Calendar.MINUTE);
        loppuPvm.clear(Calendar.SECOND);
        loppuPvm.clear(Calendar.MILLISECOND);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        initComponents();
        
    }
    
    @Override
    public void run() {
        this.setVisible(true);
        paivitaListaus();
        paivitaOtsikko();
    }
                        
    /**t
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paaPaneeli = new javax.swing.JPanel();
        listausScrollPane = new javax.swing.JScrollPane();
        Calendar alku = (Calendar)alkuPvm.clone();
        Calendar loppu = (Calendar)loppuPvm.clone();
        ArrayList<Object> tapahtumat = new ArrayList();
        tapahtumat.addAll(tili.getToistuvatTilitapahtumatAjalta(alku, loppu));
        tapahtumat.add("--");
        tapahtumat.addAll(tili.getTilitapahtumatAjalta(alku, loppu));
        listausList = new javax.swing.JList(tapahtumat.toArray());
        ylaPaneeli = new javax.swing.JPanel();
        lisaaTilitapahtumaButton = new javax.swing.JButton();
        poistaTilitapahtumaButton = new javax.swing.JButton();
        lataaTiliButton = new javax.swing.JButton();
        tallennaTiliButton = new javax.swing.JButton();
        hallitseTilitapahtumiaLabel = new javax.swing.JLabel();
        hallitseTiliaLabel = new javax.swing.JLabel();
        uusiTiliButton = new javax.swing.JButton();
        nakymaLabel = new javax.swing.JLabel();
        nakymaMeneButton = new javax.swing.JToggleButton();
        nakymaAlkuKuukausiSpinner = new javax.swing.JSpinner();
        nakymaAlkuVuosiSpinner = new javax.swing.JSpinner();
        nakymaAlkuPaivaSpinner = new javax.swing.JSpinner();
        nakymaLoppuPaivaSpinner = new javax.swing.JSpinner();
        nakymaLoppuKuukausiSpinner = new javax.swing.JSpinner();
        nakymaLoppuVuosiSpinner = new javax.swing.JSpinner();
        sivuPalkki = new javax.swing.JPanel();
        kuvausLabel = new javax.swing.JLabel();
        kuvausTextField = new javax.swing.JTextField();
        summaLabel = new javax.swing.JLabel();
        summaTextField = new javax.swing.JTextField();
        paivaLabel = new javax.swing.JLabel();
        paivaTextField = new javax.swing.JTextField();
        kuukausiLabel = new javax.swing.JLabel();
        kuukausiTextField = new javax.swing.JTextField();
        vuosiLabel = new javax.swing.JLabel();
        vuosiTextField = new javax.swing.JTextField();
        tallennaButton = new javax.swing.JButton();
        toistuvaAlkuPaivaLabel = new javax.swing.JLabel();
        toistuvaAlkuPaivaTextField = new javax.swing.JTextField();
        toistuvaAlkuKuukausiLabel = new javax.swing.JLabel();
        toistuvaAlkuKuukausiTextField = new javax.swing.JTextField();
        toistuvaAlkuVuosiTextField = new javax.swing.JTextField();
        toistuvaAlkuVuosiLabel = new javax.swing.JLabel();
        toistuvuusCheckBox = new javax.swing.JCheckBox();
        toistuvaLoppuKuukausiLabel = new javax.swing.JLabel();
        toistuvaLoppuKuukausiTextField = new javax.swing.JTextField();
        toistuvaLoppuPaivaLabel = new javax.swing.JLabel();
        toistuvaLoppuPaivaTextField = new javax.swing.JTextField();
        toistuvaLoppuVuosiTextField = new javax.swing.JTextField();
        toistuvaLoppuVuosiLabel = new javax.swing.JLabel();
        yhteenvetoPane = new javax.swing.JScrollPane();
        yhteenvetoTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buddy - pientalouden budjetoija");
        setPreferredSize(new java.awt.Dimension(800, 570));
        setResizable(false);

        listausList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listausList.setFont(new Font("Monospaced", Font.PLAIN, 12));
        listausList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listausListValueChanged(evt);
            }
        });
        listausScrollPane.setViewportView(listausList);

        lisaaTilitapahtumaButton.setText("Lisää");
        lisaaTilitapahtumaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaTilitapahtumaButtonActionPerformed(evt);
            }
        });

        poistaTilitapahtumaButton.setText("Poista");
        poistaTilitapahtumaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poistaTilitapahtumaButtonActionPerformed(evt);
            }
        });

        lataaTiliButton.setText("Lataa");
        lataaTiliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lataaTiliButtonActionPerformed(evt);
            }
        });

        tallennaTiliButton.setText("Tallenna");

        hallitseTilitapahtumiaLabel.setText("Hallitse tilitapahtumia");

        hallitseTiliaLabel.setText("Hallitse tiliä");

        uusiTiliButton.setText("Uusi");

        nakymaLabel.setText("Aikaväli");

        nakymaMeneButton.setText("Mene");
        nakymaMeneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nakymaMeneButtonActionPerformed(evt);
            }
        });

        nakymaAlkuKuukausiSpinner.setModel(new javax.swing.SpinnerNumberModel(this.alkuPvm.get(Calendar.MONTH + 1), 1, 12, 1));

        nakymaAlkuVuosiSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(this.alkuPvm.get(Calendar.YEAR)), Integer.valueOf(0), null, Integer.valueOf(1)));

        nakymaAlkuPaivaSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        nakymaLoppuPaivaSpinner.setModel(new javax.swing.SpinnerNumberModel(31, 1, 31, 1));

        nakymaLoppuKuukausiSpinner.setModel(new javax.swing.SpinnerNumberModel(this.loppuPvm.get(Calendar.MONTH) + 1, 1, 12, 1));

        nakymaLoppuVuosiSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(this.loppuPvm.get(Calendar.YEAR)), Integer.valueOf(0), null, Integer.valueOf(1)));

        nakymaAlkuVuosiSpinner.setEditor(new JSpinner.NumberEditor(nakymaAlkuVuosiSpinner, "#"));
        nakymaLoppuVuosiSpinner.setEditor(new JSpinner.NumberEditor(nakymaLoppuVuosiSpinner, "#"));

        javax.swing.GroupLayout ylaPaneeliLayout = new javax.swing.GroupLayout(ylaPaneeli);
        ylaPaneeli.setLayout(ylaPaneeliLayout);
        ylaPaneeliLayout.setHorizontalGroup(
            ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ylaPaneeliLayout.createSequentialGroup()
                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ylaPaneeliLayout.createSequentialGroup()
                        .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nakymaAlkuPaivaSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nakymaLoppuPaivaSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ylaPaneeliLayout.createSequentialGroup()
                                .addComponent(nakymaLoppuKuukausiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nakymaLoppuVuosiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ylaPaneeliLayout.createSequentialGroup()
                                .addComponent(nakymaAlkuKuukausiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nakymaAlkuVuosiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nakymaMeneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nakymaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ylaPaneeliLayout.createSequentialGroup()
                        .addComponent(uusiTiliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tallennaTiliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lataaTiliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hallitseTiliaLabel))
                .addGap(18, 18, 18)
                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ylaPaneeliLayout.createSequentialGroup()
                        .addComponent(lisaaTilitapahtumaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poistaTilitapahtumaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hallitseTilitapahtumiaLabel))
                .addGap(23, 23, 23))
        );
        ylaPaneeliLayout.setVerticalGroup(
            ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ylaPaneeliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ylaPaneeliLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lataaTiliButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ylaPaneeliLayout.createSequentialGroup()
                        .addComponent(hallitseTiliaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uusiTiliButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tallennaTiliButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(ylaPaneeliLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nakymaMeneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ylaPaneeliLayout.createSequentialGroup()
                                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nakymaAlkuKuukausiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nakymaAlkuVuosiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nakymaAlkuPaivaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nakymaLoppuKuukausiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nakymaLoppuVuosiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nakymaLoppuPaivaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ylaPaneeliLayout.createSequentialGroup()
                        .addComponent(nakymaLabel)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ylaPaneeliLayout.createSequentialGroup()
                        .addComponent(hallitseTilitapahtumiaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ylaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lisaaTilitapahtumaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poistaTilitapahtumaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        sivuPalkki.setMinimumSize(new java.awt.Dimension(200, 100));

        kuvausLabel.setText("Kuvaus");

        summaLabel.setText("Summa");

        paivaLabel.setText("pv");

        kuukausiLabel.setText("kk");

        vuosiLabel.setText("vuosi");

        tallennaButton.setText("Tallenna");
        tallennaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tallennaButtonActionPerformed(evt);
            }
        });

        toistuvaAlkuPaivaLabel.setText("pv");

        toistuvaAlkuPaivaTextField.setEnabled(false);

        toistuvaAlkuKuukausiLabel.setText("kk");

        toistuvaAlkuKuukausiTextField.setEnabled(false);

        toistuvaAlkuVuosiTextField.setEnabled(false);

        toistuvaAlkuVuosiLabel.setText("vuosi");

        toistuvuusCheckBox.setText("Toistuva tapahtuma");
        toistuvuusCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toistuvuusCheckBoxActionPerformed(evt);
            }
        });

        toistuvaLoppuKuukausiLabel.setText("kk");

        toistuvaLoppuKuukausiTextField.setEnabled(false);

        toistuvaLoppuPaivaLabel.setText("pv");

        toistuvaLoppuPaivaTextField.setEnabled(false);

        toistuvaLoppuVuosiTextField.setEnabled(false);

        toistuvaLoppuVuosiLabel.setText("vuosi");

        javax.swing.GroupLayout sivuPalkkiLayout = new javax.swing.GroupLayout(sivuPalkki);
        sivuPalkki.setLayout(sivuPalkkiLayout);
        sivuPalkkiLayout.setHorizontalGroup(
            sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sivuPalkkiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tallennaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kuvausTextField)
                    .addComponent(summaTextField)
                    .addComponent(kuvausLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(summaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sivuPalkkiLayout.createSequentialGroup()
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toistuvaAlkuPaivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toistuvaAlkuPaivaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toistuvaAlkuKuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toistuvaAlkuKuukausiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sivuPalkkiLayout.createSequentialGroup()
                                .addComponent(toistuvaAlkuVuosiLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(toistuvaAlkuVuosiTextField)))
                    .addGroup(sivuPalkkiLayout.createSequentialGroup()
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toistuvuusCheckBox)
                            .addGroup(sivuPalkkiLayout.createSequentialGroup()
                                .addComponent(paivaLabel)
                                .addGap(29, 29, 29)
                                .addComponent(kuukausiLabel)
                                .addGap(18, 18, 18)
                                .addComponent(vuosiLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sivuPalkkiLayout.createSequentialGroup()
                        .addComponent(paivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vuosiTextField))
                    .addGroup(sivuPalkkiLayout.createSequentialGroup()
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toistuvaLoppuPaivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toistuvaLoppuPaivaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toistuvaLoppuKuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toistuvaLoppuKuukausiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sivuPalkkiLayout.createSequentialGroup()
                                .addComponent(toistuvaLoppuVuosiLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(toistuvaLoppuVuosiTextField))))
                .addContainerGap())
        );
        sivuPalkkiLayout.setVerticalGroup(
            sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sivuPalkkiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kuvausLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kuvausTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(summaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(summaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paivaLabel)
                    .addComponent(kuukausiLabel)
                    .addComponent(vuosiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vuosiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(toistuvuusCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toistuvaAlkuPaivaLabel)
                    .addComponent(toistuvaAlkuKuukausiLabel)
                    .addComponent(toistuvaAlkuVuosiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toistuvaAlkuPaivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toistuvaAlkuKuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toistuvaAlkuVuosiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toistuvaLoppuPaivaLabel)
                    .addComponent(toistuvaLoppuKuukausiLabel)
                    .addComponent(toistuvaLoppuVuosiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sivuPalkkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toistuvaLoppuPaivaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toistuvaLoppuKuukausiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toistuvaLoppuVuosiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tallennaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kuvausTextField.getAccessibleContext().setAccessibleName("");

        yhteenvetoTextArea.setEditable(false);
        yhteenvetoTextArea.setColumns(20);
        yhteenvetoTextArea.setRows(5);
        yhteenvetoPane.setViewportView(yhteenvetoTextArea);

        javax.swing.GroupLayout paaPaneeliLayout = new javax.swing.GroupLayout(paaPaneeli);
        paaPaneeli.setLayout(paaPaneeliLayout);
        paaPaneeliLayout.setHorizontalGroup(
            paaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paaPaneeliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ylaPaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paaPaneeliLayout.createSequentialGroup()
                        .addGroup(paaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listausScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addComponent(yhteenvetoPane))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sivuPalkki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        paaPaneeliLayout.setVerticalGroup(
            paaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paaPaneeliLayout.createSequentialGroup()
                .addComponent(ylaPaneeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(paaPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paaPaneeliLayout.createSequentialGroup()
                        .addComponent(listausScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yhteenvetoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sivuPalkki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(paaPaneeli, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lataaTiliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lataaTiliButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lataaTiliButtonActionPerformed

    private void poistaTilitapahtumaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poistaTilitapahtumaButtonActionPerformed
        int indeksi = listausList.getSelectedIndex();
        if (indeksi != -1){
            Tilitapahtuma tapahtuma = (Tilitapahtuma)listausList.getModel().getElementAt(indeksi);
            int vastaus = JOptionPane.showConfirmDialog (null, "Haluatko varmasti poistaa tilitapahtuman?\nPoistettua tilitapahtumaa ei voi palauttaa myöhemmin.","Oletko varma?", JOptionPane.YES_NO_OPTION);
            if (vastaus == JOptionPane.YES_OPTION){
            tili.poistaTilitapahtuma(tapahtuma);
            paivitaListaus();
        }
        }
        
    }//GEN-LAST:event_poistaTilitapahtumaButtonActionPerformed

    private void lisaaTilitapahtumaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaTilitapahtumaButtonActionPerformed
        Tilitapahtuma tapahtuma = new Tilitapahtuma(
                "Uusi tilitapahtuma",
                new Summa(0),
                new GregorianCalendar());
        
        tili.lisaaTilitapahtuma(tapahtuma);
        paivitaListaus();        
    }//GEN-LAST:event_lisaaTilitapahtumaButtonActionPerformed

    private void toistuvuusCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toistuvuusCheckBoxActionPerformed
        vaihdaToistuvuusCheckBoxValinta();
    }//GEN-LAST:event_toistuvuusCheckBoxActionPerformed

    private void nakymaMeneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nakymaMeneButtonActionPerformed
        this.loppuPvm.set(
                (Integer)nakymaLoppuVuosiSpinner.getValue(), 
                (Integer)nakymaLoppuKuukausiSpinner.getValue() - 1,
                1);
        this.alkuPvm.set(
                (Integer)nakymaAlkuVuosiSpinner.getValue(), 
                (Integer)nakymaAlkuKuukausiSpinner.getValue() - 1,
                1);
        
        int alkuPaiva = (Integer)nakymaAlkuPaivaSpinner.getValue();
        if (alkuPaiva < loppuPvm.getActualMaximum(Calendar.DAY_OF_MONTH)){
            alkuPvm.set(Calendar.DAY_OF_MONTH, alkuPaiva);
        } else {
            alkuPvm.set(Calendar.DAY_OF_MONTH, alkuPvm.getActualMaximum(Calendar.DAY_OF_MONTH));
        }
        
        int loppuPaiva = (Integer)nakymaLoppuPaivaSpinner.getValue();
        if (loppuPaiva < loppuPvm.getActualMaximum(Calendar.DAY_OF_MONTH)){
            loppuPvm.set(Calendar.DAY_OF_MONTH, loppuPaiva);
        } else {
            loppuPvm.set(Calendar.DAY_OF_MONTH, loppuPvm.getActualMaximum(Calendar.DAY_OF_MONTH));
        }

        paivitaOtsikko();
        paivitaListaus();
    }//GEN-LAST:event_nakymaMeneButtonActionPerformed

    private void tallennaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tallennaButtonActionPerformed
        int valinta = listausList.getSelectedIndex();
        if (valinta != -1) {
            if (listausList.getModel().getElementAt(valinta) instanceof Tilitapahtuma){
                Tilitapahtuma tapahtuma = (Tilitapahtuma) listausList.getModel().getElementAt(valinta);
                int tiliIndeksi = tili.getTilitapahtumat().indexOf(tapahtuma);
                tapahtuma = tili.getTilitapahtumat().get(tiliIndeksi);

                tapahtuma.setKuvaus(kuvausTextField.getText());
                tapahtuma.getSumma().setSummaString(summaTextField.getText());
                tapahtuma.getAikaleima().set(
                        Integer.parseInt(vuosiTextField.getText()),
                        Integer.parseInt(kuukausiTextField.getText()) - 1,
                        Integer.parseInt(paivaTextField.getText())
                        );
                tili.getTilitapahtumat().set(tiliIndeksi, tapahtuma);
            }
            else if (listausList.getModel().getElementAt(valinta) instanceof ToistuvaTilitapahtuma){
                ToistuvaTilitapahtuma tapahtuma = (ToistuvaTilitapahtuma)listausList.getModel().getElementAt(valinta);
                int tiliIndeksi = tili.getToistuvatTilitapahtumat().indexOf(tapahtuma);
                tapahtuma.setKuvaus(kuvausTextField.getText());
                tapahtuma.getSumma().setSummaString(summaTextField.getText());
                
                tapahtuma.getAlkupvm().set(
                        Integer.parseInt(toistuvaAlkuVuosiTextField.getText()), 
                        Integer.parseInt(toistuvaAlkuKuukausiTextField.getText()) - 1, 
                        Integer.parseInt(toistuvaAlkuPaivaTextField.getText())
                        );
                tapahtuma.getLoppupvm().set(
                        Integer.parseInt(toistuvaLoppuVuosiTextField.getText()), 
                        Integer.parseInt(toistuvaLoppuKuukausiTextField.getText()) - 1, 
                        Integer.parseInt(toistuvaLoppuPaivaTextField.getText())
                        );
                tili.getToistuvatTilitapahtumat().set(tiliIndeksi, tapahtuma);
            }

            paivitaListaus();
            listausList.setSelectedIndex(valinta);
        }
        
    }//GEN-LAST:event_tallennaButtonActionPerformed

    private void listausListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listausListValueChanged
        int valinta = listausList.getSelectedIndex();
        if (valinta != -1) {
            if (listausList.getModel().getElementAt(valinta) instanceof Tilitapahtuma){
                if (toistuvuusCheckBox.isSelected()){
                    toistuvuusCheckBox.setSelected(false);
                    vaihdaToistuvuusCheckBoxValinta();
                }
                Tilitapahtuma tapahtuma = (Tilitapahtuma) listausList.getModel().getElementAt(valinta);
                summaTextField.setText(tapahtuma.getSumma().getSummaString());
                kuvausTextField.setText(tapahtuma.getKuvaus());
                paivaTextField.setText(""+tapahtuma.getAikaleima().get(Calendar.DAY_OF_MONTH));
                kuukausiTextField.setText(""+(tapahtuma.getAikaleima().get(Calendar.MONTH)+1));
                vuosiTextField.setText(""+tapahtuma.getAikaleima().get(Calendar.YEAR));
                toistuvaAlkuVuosiTextField.setText("");
                toistuvaAlkuKuukausiTextField.setText("");
                toistuvaAlkuPaivaTextField.setText("");
                toistuvaLoppuVuosiTextField.setText("");
                toistuvaLoppuKuukausiTextField.setText("");
                toistuvaLoppuPaivaTextField.setText("");
            }
            else if (listausList.getModel().getElementAt(valinta) instanceof ToistuvaTilitapahtuma){
                if (!toistuvuusCheckBox.isSelected()){
                    toistuvuusCheckBox.setSelected(true);
                    vaihdaToistuvuusCheckBoxValinta();
                }
                
                ToistuvaTilitapahtuma tapahtuma = (ToistuvaTilitapahtuma) listausList.getModel().getElementAt(valinta);
                summaTextField.setText(tapahtuma.getSumma().getSummaString());
                kuvausTextField.setText(tapahtuma.getKuvaus());
                paivaTextField.setText("");
                kuukausiTextField.setText("");
                vuosiTextField.setText("");
                toistuvaAlkuVuosiTextField.setText(""+tapahtuma.getAlkupvm().get(Calendar.YEAR));
                toistuvaAlkuKuukausiTextField.setText(""+(tapahtuma.getAlkupvm().get(Calendar.MONTH)+1));
                toistuvaAlkuPaivaTextField.setText(""+tapahtuma.getAlkupvm().get(Calendar.DAY_OF_MONTH));
                toistuvaLoppuVuosiTextField.setText(""+tapahtuma.getLoppupvm().get(Calendar.YEAR));
                toistuvaLoppuKuukausiTextField.setText(""+(tapahtuma.getLoppupvm().get(Calendar.MONTH)+1));
                toistuvaLoppuPaivaTextField.setText(""+tapahtuma.getLoppupvm().get(Calendar.DAY_OF_MONTH));
                
            }
        }
        
    }//GEN-LAST:event_listausListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hallitseTiliaLabel;
    private javax.swing.JLabel hallitseTilitapahtumiaLabel;
    private javax.swing.JLabel kuukausiLabel;
    private javax.swing.JTextField kuukausiTextField;
    private javax.swing.JLabel kuvausLabel;
    private javax.swing.JTextField kuvausTextField;
    private javax.swing.JButton lataaTiliButton;
    private javax.swing.JButton lisaaTilitapahtumaButton;
    private javax.swing.JList listausList;
    private javax.swing.JScrollPane listausScrollPane;
    private javax.swing.JSpinner nakymaAlkuKuukausiSpinner;
    private javax.swing.JSpinner nakymaAlkuPaivaSpinner;
    private javax.swing.JSpinner nakymaAlkuVuosiSpinner;
    private javax.swing.JLabel nakymaLabel;
    private javax.swing.JSpinner nakymaLoppuKuukausiSpinner;
    private javax.swing.JSpinner nakymaLoppuPaivaSpinner;
    private javax.swing.JSpinner nakymaLoppuVuosiSpinner;
    private javax.swing.JToggleButton nakymaMeneButton;
    private javax.swing.JPanel paaPaneeli;
    private javax.swing.JLabel paivaLabel;
    private javax.swing.JTextField paivaTextField;
    private javax.swing.JButton poistaTilitapahtumaButton;
    private javax.swing.JPanel sivuPalkki;
    private javax.swing.JLabel summaLabel;
    private javax.swing.JTextField summaTextField;
    private javax.swing.JButton tallennaButton;
    private javax.swing.JButton tallennaTiliButton;
    private javax.swing.JLabel toistuvaAlkuKuukausiLabel;
    private javax.swing.JTextField toistuvaAlkuKuukausiTextField;
    private javax.swing.JLabel toistuvaAlkuPaivaLabel;
    private javax.swing.JTextField toistuvaAlkuPaivaTextField;
    private javax.swing.JLabel toistuvaAlkuVuosiLabel;
    private javax.swing.JTextField toistuvaAlkuVuosiTextField;
    private javax.swing.JLabel toistuvaLoppuKuukausiLabel;
    private javax.swing.JTextField toistuvaLoppuKuukausiTextField;
    private javax.swing.JLabel toistuvaLoppuPaivaLabel;
    private javax.swing.JTextField toistuvaLoppuPaivaTextField;
    private javax.swing.JLabel toistuvaLoppuVuosiLabel;
    private javax.swing.JTextField toistuvaLoppuVuosiTextField;
    private javax.swing.JCheckBox toistuvuusCheckBox;
    private javax.swing.JButton uusiTiliButton;
    private javax.swing.JLabel vuosiLabel;
    private javax.swing.JTextField vuosiTextField;
    private javax.swing.JScrollPane yhteenvetoPane;
    private javax.swing.JTextArea yhteenvetoTextArea;
    private javax.swing.JPanel ylaPaneeli;
    // End of variables declaration//GEN-END:variables

    private void paivitaOtsikko() {
        this.setTitle("Buddy - pientalouden budjetoija - "
                + this.tili.getNimi() 
                + " - "
                +this.alkuPvm.get(Calendar.DAY_OF_MONTH)
                +"/"
                + (this.alkuPvm.get(Calendar.MONTH) + 1) 
                +"/"
                +this.alkuPvm.get(Calendar.YEAR) 
                +" - "
                +this.loppuPvm.get(Calendar.DAY_OF_MONTH)
                +"/"
                + (this.loppuPvm.get(Calendar.MONTH) +1)
                + "/"
                + this.loppuPvm.get(Calendar.YEAR)
        );
    }

    private void paivitaListaus() {
        Calendar alku = (Calendar)alkuPvm.clone();
        Calendar loppu = (Calendar)loppuPvm.clone();
        
        ArrayList<Object> tapahtumat = new ArrayList();
        tapahtumat.addAll(tili.getToistuvatTilitapahtumatAjalta(alku, loppu));
        tapahtumat.add("--");
        tapahtumat.addAll(tili.getTilitapahtumatAjalta(alku, loppu));
        
        listausList.setListData(tapahtumat.toArray());
        
//        for (Object o : tapahtumat){
//            System.out.println(o);
//        }
    }

    private void vaihdaToistuvuusCheckBoxValinta() {
        paivaTextField.setEnabled(!paivaTextField.isEnabled());
        kuukausiTextField.setEnabled(!kuukausiTextField.isEnabled());
        vuosiTextField.setEnabled(!vuosiTextField.isEnabled());
        
        toistuvaAlkuPaivaTextField.setEnabled(!toistuvaAlkuPaivaTextField.isEnabled());
        toistuvaAlkuKuukausiTextField.setEnabled(!toistuvaAlkuKuukausiTextField.isEnabled());
        toistuvaAlkuVuosiTextField.setEnabled(!toistuvaAlkuVuosiTextField.isEnabled());
        toistuvaLoppuPaivaTextField.setEnabled(!toistuvaLoppuPaivaTextField.isEnabled());
        toistuvaLoppuKuukausiTextField.setEnabled(!toistuvaLoppuKuukausiTextField.isEnabled());
        toistuvaLoppuVuosiTextField.setEnabled(!toistuvaLoppuVuosiTextField.isEnabled());
    }
}
